version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: bun
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
