on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

name: Validate games.json
jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v4.2.2

      - name: 🚧 Setup Node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 19.0.0

      - name: 🤖 Setup Project
        run: 'yarn'

      - name: 🔎 Check Validity
        run: 'yarn validate'
